services:
  db:
    image: postgres:16
    container_name: dwh_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_pw
      POSTGRES_DB: dwh_chatbot
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: dwh_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db_data:
